spring:
  application:
    name: budgetTool
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test01
#    url: jdbc:postgresql://localhost:5432/budget_tool
    username: postgres
    password: 6477
  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kimjaehyeong92@gmail.com
    password: sqmk norh jxms onwm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-milis: 1800000


#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp



server:
  port: 8080
  servlet:
    context-path: /budgetTool
    encoding:
      charset: utf-8
      enabled: true

# 에러 페이지 설정
error:
  whitelabel:
    enabled: false
  path: /error
  include-message: always
  include-binding-errors: always
  include-stacktrace: never
  include-exception: false

token:
  access: AC_
  refresh: REF_
